### ISSUE TITLE
Would it make sense to make it more clear that ps-rosetta needs to be present in order for whoami.init() to work?

### ISSUE THREAD

**Issue by nhoffmann** [spring-media/ps-web-apis#15]
I worked on integrating whoami into one of Team Loyalty's frontend widgets and it worked like a charm! 
The only downside was, that I did not know that ps-rosetta needs to be present in the page and it took me some time to find that out and only after asking a fellow dev. 
Would it make sense to add that information to the README? Maybe it's clear to everyone else and I am just a total noob on this :)

**Comment by moegelin** [comment]
It would make sense 👍
